### ISSUE TITLE
Gallery with makers 

### ISSUE THREAD

**Issue by surak** [aceisace/Inky-Calendar#104]
Hi, how about a Gallery with the picture of the implementation in the wild?

**Comment by aceisace** [comment]
@surak 
You mean something like a hall of fame containing pictures of the Inky-Calendar from different users?

**Comment by surak** [comment]
Genau!

**Comment by aceisace** [comment]
@surak 
OK, added a new page 'Hall of Fame' in the wiki: [Hall-of-Fame](https://github.com/aceisace/Inky-Calendar/wiki/hall-of-fame).

**Comment by aceisace** [comment]
@surak Thanks for your mail. I've added the content to the Hall of fame page!

**Comment by aceisace** [comment]
Closing this issue as the hall of fame has been created. If you feel a need to re-open this issue, please feel free to do so.

**Comment by surak** [comment]
I will! The link to that image is broken :-)

https://github.com/aceisace/Inky-Calendar/wiki/hall-of-fame

**Comment by aceisace** [comment]
@surak Fixed!
