### ISSUE TITLE
Error: BETA doesn't appear to be putting modules at the correct heights

### ISSUE THREAD

**Issue by emilyboda** [aceisace/Inky-Calendar#125]
I noticed that my modules were pretty close together and they didn't seem to be using the full height of the display. The last line of my module in the picture below is supposed to be on the very last line of the display.

![regular](https://user-images.githubusercontent.com/9170143/84066011-4ae48b80-a993-11ea-8244-3a1e51111fdf.jpg)

I removed the "+ y" from two lines in /inkycal/main.py so they now read:
line 280: `im1_cursor += section_size[1]`
line 305: `im2_cursor += section_size[1]`

And the image appears to now be taking up the correct amount of space:

![fixed maybe](https://user-images.githubusercontent.com/9170143/84066014-4d46e580-a993-11ea-8cc2-e29208b8e198.jpg)

I do not know if removing the + y was the correct way of doing it, but I thought I'd share my observations. There's probably more edits that need to be done, since it now appears that the agenda is shorter than it needs to be.

**Comment by aceisace** [comment]
@emilyboda I've fixed this problem in the BETA so I'm closing this issue now. Feel free to re-open this issue if somthing isn't working as expected.
