### ISSUE TITLE
Bug: web-ui doesn't format urls correctly

### ISSUE THREAD

**Issue by emilyboda** [aceisace/Inky-Calendar#129]
This is for the BETA!

When you add two or more URLs to the iCal URL bar in the online settings.json file generator in the format requested, the file that is generated adds single quote between the URLs and double quotes at the beginning and end. 

For example, if you input the following into the online UI:
`'ulr_a.com','url_b.com','url_c.com'`

The file generated will show the following:
```
"ical_urls": [
			"ulr_a.com','url_b.com','url_c.com"
		 ]
```
Notice the single quotes between the URLs, but double quotes on the outer edges. This is an incorrectly formatted list and will result in an error if you try to use the iCal URLs in any module.

**Comment by aceisace** [comment]
@emilyboda OK, this should hopefully be fixed now. The fix allows:
* Adding urls without quotes: `url1, url2, url3`
* Directly converts urls into a array (list) instead of string replacment
* Generated correct settings file, i.e.:
```python
                   "ical_urls": [
					"url1",
					"url2",
					"url3"
				]
```

**Comment by aceisace** [comment]
OK, did some testing with the updated web-ui. The problem seems to be fixed now :). 
I'll be closing this issue. If you feel a need to re-open this issue, please feel free to do so.
