### ISSUE TITLE
Setup: Getting the Raspberry PI Zero Ready instructions

### ISSUE THREAD

**Issue by lumpynose** [aceisace/Inky-Calendar#142]
The link is https://github.com/aceisace/Inky-Calendar#getting-the-raspberry-pi-zero-w-ready

Step 1 says "After flashing Raspbian Buster (with Desktop), set up Wifi on the Raspberry Pi Zero W by copying the file wpa_supplicant.conf (from above) to the /boot directory and adding your Wifi details in that file." and the link to Raspbian Buster takes you to a page where the link to Raspbian Buster is for installing it on an old PC or laptop.  The links above that on the Raspberry Pi page don't say anything about Buster.  I'm concerned that a newbie may not realize that they are installing Raspian on their PC.  Wouldn't it be better, instead of Raspian Buster, to say "Raspberry Pi OS with desktop" or "Raspberry Pi OS with desktop and recommended software"?

**Comment by aceisace** [comment]
@lumpynose Thanks for the report. Sorry for getting back a bit late, I've replaced the name from Raspbian Buster and link to Raspberry Pi OS and updated the link to point at the correct place.

Closing this issue as it has been resolved. If you feel a need to re-open this issue, please feel free to do so again.
