### ISSUE TITLE
Settings file not configured

### ISSUE THREAD

**Issue by surak** [aceisace/Inky-Calendar#40]
It does this: 

![IMG_2181](https://user-images.githubusercontent.com/878399/62839614-3a3c8980-bc8c-11e9-8505-26fef59d7fd1.JPG)

**Comment by aceisace** [comment]
@surak  
Hi, I think the problem might be that the settings file is not configured yet. Could you please take a look at this section on how to generate the settings file?  [Creating a settings file](https://github.com/aceisace/Inky-Calendar#adding-details-to-the-programm)

**Comment by surak** [comment]
As I have the Pi inside of a glued box, connecting it to a screen is not an option. I'll scp the html and see what it does, then. I would rather have a functional settings file as it was before, though.

**Comment by surak** [comment]
Ok, now I understand. That is the new "default" view. I'm not sure it's a good default, though.
