### ISSUE TITLE
Multiple issues with calendars

### ISSUE THREAD

**Issue by surak** [aceisace/Inky-Calendar#41]
I have an "abfallkalender" - some app creates a calendar with the days of garbage here in Germany, which you know how it works.

As this thing creates a calendar, I shared it from iCloud, and it creates a webcal link. As this is just the garbage, here is the example URL:

[Link as webcal
](webcal://p33-caldav.icloud.com/published/2/MTMxNDQ2NDAxMzE0NDY0MIs4JThLcd2nh4XXItgMUl_XVRv5v22MZ9br9jNqMlgQR4sRlGVaofsVp55wQ10ggLVBxDxL7yZCz0dDVMxQTHY)

If you just paste the webcal url, it fails: 

```
Traceback (most recent call last):
  File "E-Paper.py", line 527, in <module>
    main()
  File "E-Paper.py", line 345, in main
    decode = str(urlopen(icalendars).read().decode())
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 489, in _open
    'unknown_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1324, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: webcal>
```

If you change the protocol to http, it downloads a normal ics file. This file is not readable by the ics module being used here:

```
Internet connection test passed

Fetching events from your calendar

Traceback (most recent call last):
  File "E-Paper.py", line 527, in <module>
    main()
  File "E-Paper.py", line 352, in main
    ical = Calendar(decode)
  File "/home/pi/.local/lib/python3.5/site-packages/ics/icalendar.py", line 69, in __init__
    self._populate(container[0])  # Use first calendar
  File "/home/pi/.local/lib/python3.5/site-packages/ics/component.py", line 52, in _populate
    .format(container.name, extractor.type))
ValueError: A VCALENDAR must have at least one PRODID
```

So, I took the public link and imported into a google calendar, which I shared:

[https://calendar.google.com/calendar/ical/lmnhsglq59s57uj8bi8jlgjl15psjp0n%40import.calendar.google.com/public/basic.ics](public version)

This works. And I love the new version.

**Comment by aceisace** [comment]
@surak 
Hi Alex, I'm glad you like the new version :)
That's interesting. I did exppect webcal iCalendar URLs to work, but it seems as though that is not the case here. In regards to the http protocol error, which version of ics and arrow are you using?

Thanks for sharing the info on how to get a webcal working with the software. It seems as though google is still the best option.

**Comment by surak** [comment]
No clue. I fresh-installed the thing, and it gave me the error. Should I check?

**Comment by aceisace** [comment]
@surak 
Sorry for the late reply. 
I'll check this up myself and will provide the fix in the new release.

**Comment by surak** [comment]
Hi, thanks! Or just let people know that it is a limitation of the ics library. Perhaps I should test it more and report to them!

**Comment by aceisace** [comment]
@surak 
I'll add a note about the limitation of the ics library when I'm back. If you could test the ics library more, that would be helpful.

**Comment by aceisace** [comment]
@surak 
Hi Alex, I've added a note on the readme of the repo about the limitation of the ics library in regards of webcal based calendars.

As this issue is now resolved, I'll be closing this issue now. If you feel a need to re-open the issue, please feel free to do so.

**Comment by surak** [comment]
How about this?
https://github.com/C4ptainCrunch/ics.py/issues/157
