### ISSUE TITLE
Python 3.7 default 

### ISSUE THREAD

**Issue by ahobitt** [aceisace/Inky-Calendar#45]
The calendar didn't auto start at boot. I installed supervisor as described in the wiki, but the new default version for python seems to be python3.7.

Suggestion:
Change Line 257 in Installer-with-debug.sh from
`command = sudo /usr/bin/python3.5 /home/pi/Inky-Calendar/Calendar/E-Paper.py ` to `command = sudo /usr/bin/python3.7 /home/pi/Inky-Calendar/Calendar/E-Paper.py `

Everything else works like a charm, even for my Nextcloud Calender. Thank you!

**Comment by KunalGautam** [comment]
I think python3 can be better option since it will support python3.x

`command = sudo /usr/bin/python3 /home/pi/Inky-Calendar/Calendar/E-Paper.py`

**Comment by ahobitt** [comment]
That is true.

**Comment by aceisace** [comment]
@ahobitt @KunalGautam 
Well noted with thanks. I've changed the mentioned line so it defaults to python3 now. Hopefully this should resolve the issue with the auto-start.

I'll be closing this issue now. If you feel a need to re-open this issue, please feel free to do so.
