### ISSUE TITLE
VERSION file with the version number

### ISSUE THREAD

**Issue by surak** [aceisace/Inky-Calendar#47]
Since you have version numbers now, it could be that either a file named VERSION containing the current version, or at least github tags, where one could see which one is the current one (I keep my fork in line with yours and I have no clue which version is it hehehe)

Feel free to close this if you disagree, of course!

**Comment by aceisace** [comment]
@surak 
There is a [CHANGELOG file](https://github.com/aceisace/Inky-Calendar/blob/Stable/Changelog.md) I created to give an overview of all the changes of each release. 
Additionally, this sticker here on the README page also shows the current release. which is v1.6:
<img src="https://user-images.githubusercontent.com/29558518/67903572-370ab880-fb6c-11e9-9a03-79666107ac5d.png" width="700">

Is there still a need to create the version file?

**Comment by aceisace** [comment]
I'm closing this issue as the purpose of this issue had already been fulfilled. If you feel  a need to re-open this issue, please feel free to do so.
