### ISSUE TITLE
Feature request: Add support for more E-Paper displays

### ISSUE THREAD

**Issue by kabal00** [aceisace/Inky-Calendar#65]
Hi everybody,

Great work with the software!

is it possible to use the Inky-Calendar with the new Waveshare 7.5 inch with a higher resolution (800 x 480)? I tried to change the libraries without any success. 

Thanks in advance.

**Comment by aceisace** [comment]
Hi @kabal00 and thanks for your comment. Support for the new 7.5" is in planning and will be added soon once the current known bugs are fixed.

Once further progress is made, I'll post an update in this thread.

**Comment by aceisace** [comment]
OK, I'm back @kabal00 now. I've started working on the support for the new E-Paper displays. Unfortunately, it might take a bit longer than expected (~1-2 weeks) as I have to update nearly everything in the driver files. Reason being is that waveshare uses a new approach to render images on the E-Paper displays.

As the modification required are bigger than expected, a new release will be pusblished to support this feature. Before pushing the changes on the master branch, I might ask you to test the new version of the Inky-Calendar software.

**Comment by kabal00** [comment]
Hey aceisace,

sounds Great and I will verify the new software. 

Thanks for your fast response and I am looking forward to your new software release.

**Comment by aceisace** [comment]
Hi @kabal00 ,
I'm nearly finished with the integration of several more displays. For now, the following E-Paper displays are supported:
* 4.2" E-Paper black-white
* 4.2" E-Paper black-white-red/yellow
* 5.83" E-Paper black-white
* 5.83" E-Paper black-white-red/yellow
* 7.5" E-Paper black-white (640x384px)
* 7.5" E-Paper black-white-red/yellow (640x384px)
* 7.5" E-Paper black-white (800x400px)
* 7.5" E-Paper black-white-red/yellow (800x400px)

I've attached an image below on how the software looks like on the 7.5" black-white-yellow (800x400px):
<img src="https://user-images.githubusercontent.com/29558518/72624306-fe96a180-3946-11ea-8450-6a1ac1368b8e.JPG" width=400>
Of course it still needs some fine-tuning (some letters are shown half in yellow and half in black, but other than that, it works!

That being the case, please let me know in a comment when you have some time to test the new version. That would be a great help to check for bugs and errors :)

**Comment by Ribitsch** [comment]
> Hi @kabal00 ,
> I'm nearly finished with the integration of several more displays. For now, the following E-Paper displays are supported:
> 
> * 4.2" E-Paper black-white
> * 4.2" E-Paper black-white-red/yellow
> * 5.83" E-Paper black-white
> * 5.83" E-Paper black-white-red/yellow
> * 7.5" E-Paper black-white (640x384px)
> * 7.5" E-Paper black-white-red/yellow (640x384px)
> * 7.5" E-Paper black-white (800x400px)
> * 7.5" E-Paper black-white-red/yellow (800x400px)
> 
> I've attached an image below on how the software looks like on the 7.5" black-white-yellow (800x400px):
> <img alt="" width="400" src="https://user-images.githubusercontent.com/29558518/72624306-fe96a180-3946-11ea-8450-6a1ac1368b8e.JPG">
> Of course it still needs some fine-tuning (some letters are shown half in yellow and half in black, but other than that, it works!
> 
> That being the case, please let me know in a comment when you have some time to test the new version. That would be a great help to check for bugs and errors :)

That sound awesome!
Would like test it out, but I am still waiting for my E-Ink Display to arrive.

**Comment by aceisace** [comment]
No problem, @Ribitsch . Just let me know when it has arrived. Thanks in advance.

**Comment by aceisace** [comment]
@Ribitsch I'm closing this issue as this feature has now been implemented. If you feel something isn't working right, please open a new issue. Thanks for understanding.
