### ISSUE TITLE
Installer points to incorrect location of main file

### ISSUE THREAD

**Issue by Ribitsch** [aceisace/Inky-Calendar#66]
Hello,

I just wanted to tell, that the path to start the application is wrong in the readme.
See the image below:
Instead of 
"python3 /home/pi/Inky-Calendar/Calendar/inkycal.py"
the correct path is:
"python3 /home/pi/Inky-Calendar/modules/inkycal.py"

(Looks like the files were reorganized at some point?)

Looking forward to test on the new display, once it has arrived!

All the best
Chris

<img width="1605" alt="image" src="https://user-images.githubusercontent.com/13382038/72664388-85a65100-39fd-11ea-8539-95ff040aa085.png">

**Comment by aceisace** [comment]
@Ribitsch Hi Chris,
Thanks for finding the incorrect path. Indeed the files were re-organised recently. I must have forgotten to fix the path. 

I've fixed the path now :) https://github.com/aceisace/Inky-Calendar/commit/7945f1b2acd94d1f77fc6e3d09ff7b8cfa528df1
