### ISSUE TITLE
Suggestion: font sizes belong to settings.py

### ISSUE THREAD

**Issue by surak** [aceisace/Inky-Calendar#84]
I have the calendar in a corner, and my vision is not that sharp as it used to be. Plus, our font rendering is not optimal.

Because of that, I use bigger fonts... And this configuration belongs to the settings, no?

**Comment by aceisace** [comment]
@surak  Hi surak, thanks for this sugegstion.

The idea was that:
* Required settings belong to settings.py (change via web-ui)
* Optional settings belong to configuration.py (change manually, for advanced users only)

As the fontisze for each module isn't strictly required, fontsizes are found and set in configuration.py.

But I'd like to know the opinion of @vitasam and  @Atrejoe on this regard.

**Comment by aceisace** [comment]
Will work on this once the situation gets better, apologies for the delay.

**Comment by aceisace** [comment]
@surak 
Hi, the new release will have classes with configurable options (`inkycal_weather.fontsize = 13`). The configuration.py will not exist anymore. Any configuration belonging to a module should be set by that module. This will be a step to a more maintainable code.

A few improvements regarding the rendering of text are also underway, so hopefully there will be some more improvements to look forward to.

**Comment by aceisace** [comment]
Closing this issue due to refactoring of the software (see /dev_v2 branch). If you feel a need to re-open this issue, please feel free to do so.
