### ISSUE TITLE
Calendar events rectangles are in wrong places

### ISSUE THREAD

**Issue by vitasam** [aceisace/Inky-Calendar#85]
Calendar in `/dev` branch has an issue - it shows (some) Wednesdays marked as event, but some actual events are not marked. `/master` branch is OK with the same calendar URL.

**Comment by aceisace** [comment]
Will work on this once the situation gets better, apologies for the delay.

**Comment by vitasam** [comment]
This is what the latest `dev `shows for my calendar's events:
![inkycal_calendar_wrong_rectangles](https://user-images.githubusercontent.com/5597505/79604498-dd388380-80f6-11ea-8aca-0f708694fe80.png)

**Comment by vitasam** [comment]
Is this a problem only with my iCalendar or someone can reproduce it?
