### ISSUE TITLE
Incompatible version of python-dateutil

### ISSUE THREAD

**Issue by DevelopAlex** [aceisace/Inky-Calendar#87]
**Description**
Exception "RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware" in modules\inkycal_icalendar.py:65:

    except Exception as e:
        print('Something went wrong while parsing recurring events:' + str(e))

**Reason**
`ics` is not compatible with `dateutil` 2.7+.
Also see https://github.com/pimutils/khal/issues/767[https://github.com/pimutils/khal/issues/767](https://github.com/pimutils/khal/issues/767) 

**Solution**
Downgrade to `dateutil` 2.6.1 which is the latest working version [version](https://pypi.org/project/python-dateutil/#history).
Add `python-dateutil==2.6.1` to requirements.txt

**Comment by aceisace** [comment]
Will work on this once the situation gets better, apologies for the delay.
