### ISSUE TITLE
Bug: inkycal_agenda: Problem with parsing of recurring events

### ISSUE THREAD

**Issue by Ribitsch** [aceisace/Inky-Calendar#97]
As can be seen in the image, the same events are printed multiple times (even on the false date)

Happens for:
-) Recurring All Day Events (e.g. Birthdays)
-) All Day Events (e.g. Holiday)

![image0](https://user-images.githubusercontent.com/13382038/79256026-9db83000-7e87-11ea-9a16-15637db9a071.jpg)

**Comment by aceisace** [comment]
@Ribitsch For the new release, I've switched from the ics library (currently used to parse icalendars) to the icalendar library. This will hopefully fix all currently related issues to the (correct) parsing of events. 

On that note, I'd like to ask you to test the new icalendar parser from here:
[new ical parser](https://github.com/aceisace/Inky-Calendar/blob/dev_ver2_0/inkycal/modules/ical_parser.py)

After copying this file to the rpi, please run the file and set it up:
```python
#  init class
a = icalendar()
# url can be a string or list of strings (containing urls): 'URL1' or ['URL1', 'URL2', 'URL3']
a.load_url('url')
# parse events from now until the next 4 weeks (applies to recurring events as well)
a.get_events(arrow.now(), arrow.now().shift(weeks=4))
a.show_events()
```

Do the events match up with your calendar?

**Comment by Ribitsch** [comment]
Thanks for the info, I’ll try it asap

**Comment by aceisace** [comment]
@Ribitsch Thanks for testing the new parser. It seems that this specific bug has been solved in the /dev_v2 branch. Once the new release hits beta, I'll notify you once again so you can test it :)

**Comment by aceisace** [comment]
@Ribitsch 
The new release is now available as BETA. To find out more, please check here: #75 
It should fix most of the current issues, but further testing is required. If you check out the BETA, please let me know if this issue has been resolved. Thanks in advance!

**Comment by aceisace** [comment]
Closing this issue as the bugfix has been implemented in the development branch. If this issue happens again, feel free to re-open this issue.
