### ISSUE TITLE
Development independent of hardware

### ISSUE THREAD

**Issue by Atrejoe** [aceisace/Inky-Calendar#98]
In order to speed up development, most development tasks (apart from actual rending) can be developed on more powerful machines and in richer environments than running this on a Pi zero.

Think of IDEs like VS Code, PyCharm and various git GUIs.

# Optional side-quest
It would be nice if we can have some development options (with sensible defaults) like:
- [x] Skip actual rending / sending to E-Ink panel
- [x] Logging verbosity
- [x] Show error details on screens (stack trace, besides message)

**Comment by vitasam** [comment]
Hi @aceisace , should `feature/issue98_image_only_rendering` be merged in to `dev` branch?

**Comment by aceisace** [comment]
@vitasam Yes, it can and should be merged. Merging now...

**Comment by vitasam** [comment]
@aceisace I merged yet, could you double check that everything is Ok?

**Comment by vitasam** [comment]
Tested it in `dev` brunch - works as expected. Closing the issue.
